api/app/config.py

feat(config): use australian simulated numbers

---

.circleci/config.yml
Makefile
ci/Makefile
ci/Pipfile
ci/remove_feat_prefix.py
ci/undeploy_closed_branches.py

when they get merged or removed

feat(branches): clean up feature branches

---

admin/app/templates/components/page-footer.html
admin/app/templates/views/api/callbacks.html
admin/app/templates/views/api/keys.html
admin/app/templates/views/api/whitelist.html
admin/app/templates/views/two-factor-email.html
admin/app/templates/views/two-factor.html

also got rid of misleading back arrow.
the ticket would have preferred for a larger restructure to happen but
it's just too much of a change to do at this stage.

feat(two-factor): change link text, reworded

---

.circleci/config.yml

Adding already green tests to CI

Adding tests to ci

---

admin/Pipfile
admin/Pipfile.lock
admin/app/config.py
admin/app/main/__init__.py
admin/app/main/s3_client.py
admin/app/main/views/email_branding.py
admin/app/main/views/service_settings.py
admin/app/main/views/static_logo.py
admin/app/templates/views/email-branding/manage-branding.html
admin/app/utils.py
api/app/delivery/send_to_providers.py
utils/notifications_utils/s3.py
utils/setup.py

Our cloud team provisions new s3 credentials per-bucket. this makes it
impossible to access multiple buckets using a set of global creds.
Here we manage s3 connections by bundling a set of credentials together
with the bucket name they are allowed to access.

feat(logo): use new bucket, with separate creds

---

admin/app/templates/views/features.html
api/Pipfile.lock

We specifically point out that branding can be customised but we will
work with the service to use their branding rather than just allowing
whatever branding the service asks for.
We don't give any commitments around sending messages yet.

feat(features): change some copy

---

.circleci/config.yml
admin/manifest-dev.yml
admin/manifest.yml
api/manifest-dev.yml
api/manifest.yml
status/manifest.yml

~~Hoping this fixes https://circleci.com/gh/govau/notify/5454~~ Doesn't. See https://github.com/cloudfoundry/cli/issues/1445

feat(cf): bump cf zdt to 0.0.8

---

utils/notifications_utils/formatters.py
utils/tests/test_formatters.py

Unwind custom markdown

---

admin/package-lock.json
admin/package.json

See:
- https://nvd.nist.gov/vuln/detail/CVE-2018-16469
- https://hackerone.com/reports/381194
- https://github.com/yeikos/js.merge/issues/27
- https://github.com/sasstools/sass-lint/issues/1229

fix(admin): update "merge" dep vulnerability

---

admin/app/templates/views/signedout.html

https://notify-f-div.apps.y.cld.gov.au

Adding div back

---

admin/app/assets/stylesheets/govuk-template.scss

Fixing minor css issue

---

api/app/celery/reporting_tasks.py
api/app/commands.py
api/app/models.py
api/migrations/versions/0206_rename_billing_date_col.py
api/tests/app/celery/test_reporting_tasks.py

Will rebase once #151 is merged

Rename billing date column

---

admin/manifest.yml
api/manifest.yml

Increasing instance count to 2 for admin + api for HA

Increase instance counts for end-user facing services

---

docs/src/components/sidenav.js
docs/src/pages/index.js

the old one was too big for mobile, and really didn't say much

fix(docs): update docs index header

---

.circleci/config.yml
api/Makefile
api/Pipfile
api/Pipfile.lock
api/manifest.yml

This reverts commit 7944def4a956f9ad9434c9aa8408c4069fec5526.

Revert "Adding new-relic configuration (#144)"

---

admin/app/config.py

Waiting on confirmation to merge

feat(config): remove basic auth in live

---

admin/app/templates/views/pricing.html

Remove public references to these agreements for now.

feat(pricing): data sharing + financial agreement

---

.circleci/config.yml

Issue's been rolled back so we shouldn't have to rely on the workaround anymore: https://github.com/lovell/sharp/issues/1632

Remove sharp workaround

---

admin/app/templates/views/signedout.html
admin/app/templates/views/terms-of-use.html

add sections about team, pricing, and agency usage

feat(copy): update landing page and terms of use

---

admin/app/assets/javascripts/sentry.js
admin/application.py
admin/gulpfile.babel.js
api/application.py
api/run_celery.py

should align release along frontend, admin, celery, api

feat(sentry): track releases using commit sha

---

admin/package-lock.json
admin/package.json

this should clear out a bunch of sentry noise from chrome extensions
https://github.com/getsentry/sentry-javascript/issues/1567
https://github.com/getsentry/sentry-javascript/pull/1713

Feat update sentry

---

docs/src/components/core/heading.js

¶ ¶ ¶ ¶
¶ ¶ ¶ ¶
¶ ¶ ¶ ¶
¶ ¶ ¶ ¶

docs: use the pilcrow

---

docs/src/components/layout.js
docs/src/mdx-layout.js

https://notify-docs-f-meta-title.apps.y.cld.gov.au/

Make docs title dynamic

---

admin/app/main/forms.py
admin/app/main/views/platform_admin.py
admin/app/main/views/service_settings.py
admin/app/notify_client/service_api_client.py
admin/app/templates/components/form.html
admin/app/templates/components/page-header.html
admin/app/templates/views/platform-admin/_base_template.html
admin/app/templates/views/platform-admin/reports.html
admin/app/templates/views/service-settings.html
admin/app/templates/views/service-settings/set-service-setting.html
admin/tests/__init__.py
admin/tests/app/main/views/test_platform_admin.py
admin/tests/app/main/views/test_service_settings.py
api/app/dao/date_util.py
api/app/dao/organisation_dao.py
api/app/dao/services_dao.py
api/app/models.py
api/app/schemas.py
api/app/service/rest.py
api/app/status/healthcheck.py
api/migrations/versions/0200_create_admin_user.py
api/migrations/versions/0211_add_go_live_user.py
api/migrations/versions/0212_add_count_as_live.py
api/migrations/versions/0213_admin_user_auth_type.py
api/tests/app/dao/test_services_dao.py
api/tests/app/db.py
api/tests/app/job/test_rest.py
api/tests/app/service/test_rest.py
api/tests/app/status/test_status.py
api/tests/conftest.py

~Once we do these, we can add a similar one for trial mode services which is more useful to use right now.~

admin: pull in CSV report from GDS

---

admin/app/assets/stylesheets/components/list-entry.scss
admin/app/assets/stylesheets/components/textbox.scss

make sure that padding and font-family are the same for our backing
textbox and the overlay that highlights the text above it

admin: align personalisation highlight

---

utils/notifications_utils/formatters.py
utils/notifications_utils/jinja_templates/email_template.jinja2
utils/notifications_utils/template.py
utils/tests/test_template_types.py

See https://github.com/alphagov/notifications-utils/commit/368b55eb509035e116291ac6346f658bc4b089fc

email: add preheader/preview to HTML

---

docs/src/code-examples/generate-template-preview/go.mdx
docs/src/code-examples/generate-template-preview/node.mdx
docs/src/code-examples/sending-emails/go.mdx
docs/src/code-examples/sending-emails/node.mdx
docs/src/code-examples/sending-texts/go.mdx
docs/src/code-examples/sending-texts/node.mdx
docs/src/content/sending-messages.mdx

Also update the Go reference to use an interface{} for Value instead of
a string.

docs: add usage for personalisation list fields

---

api/app/dao/permissions_dao.py
api/app/dao/service_user_dao.py
api/app/dao/services_dao.py
api/app/dao/users_dao.py
api/app/models.py
api/app/user/rest.py
api/tests/app/conftest.py
api/tests/app/dao/test_services_dao.py
api/tests/app/dao/test_users_dao.py
api/tests/app/db.py
api/tests/app/user/test_rest.py

See https://github.com/alphagov/notifications-api/commit/87cb6f25974d394a8fa1b8f9cd7abe8aa28e05a7
See https://github.com/alphagov/notifications-api/commit/33166f3fb2825b360ab19569f08414dcf52a886a

api: add ability to archive a user (from GDS)

---

api/app/models.py
api/app/user/rest.py
api/tests/app/user/test_rest.py

Doing this in preparation for incoming changes from GDS.

api: return services in get_orgs_and_services

---

api/app/dao/users_dao.py
api/app/schemas.py
api/app/user/rest.py
api/app/utils.py
api/tests/app/user/test_rest.py

In preparation for allowing admin to perform platform admin tasks on
users.

api: add find_users_by_email

---

api/app/dao/fact_notification_status_dao.py
api/app/models.py
api/app/utils.py
api/migrations/versions/0231_add_ft_notification_status.py
api/tests/app/dao/test_fact_notification_status_dao.py
api/tests/app/db.py
api/tests/app/platform_stats/test_rest.py
api/tests/app/test_utils.py

See https://github.com/alphagov/notifications-api/commit/bb9eb367b76b566ffdecb16c76e67d9a0a83c35d
See https://github.com/alphagov/notifications-api/commit/4d27972c9066ff5112f2a8250f289f5863cbdebd

api: add ft_notification_status model

---

admin/app/assets/stylesheets/govuk-template.scss

checkbox and radio psuedo elements were affected.
also we use a consistent outline for radio inputs

admin/inputs: fix offset from border-box update

---

admin/.flake8
admin/app/main/forms.py
admin/tests/app/main/test_choose_time_form.py

The previous implementation was not taking into account AET.

admin: fix options for scheduled "Later today"

---

admin/app/templates/views/usage-with-letters.html

admin: hide price shown in Usage

---

admin/app/templates/views/usage-with-letters.html
api/migrations/versions/0237_update_sms_rates.py
api/migrations/versions/0240_update_sms_rates.py

Rebased and migration ID changed.

admin: fix incorrect price

---

admin/app/main/forms.py
admin/app/main/views/api_keys.py
admin/app/notify_client/service_api_client.py
admin/tests/app/main/views/test_api_integration.py
admin/tests/conftest.py
api/Makefile
api/app/service/callback_rest.py
api/tests/app/service/test_callback_rest.py

JIRA- https://govausites.atlassian.net/browse/NOT-193

admin: fix service api callback form to accept empty values

---

admin/app/main/views/dashboard.py
api/app/commands.py

We will eventually remove or change the billing in line with the UKs
models, however this should let us run the command again to fix up bad
monthly billing data containing old rates.

api: fix populate-monthly-billing cmd

---

admin/app/main/views/choose_account.py
admin/app/models/__init__.py
admin/app/notify_client/user_api_client.py

pulls in some changes from gov.uk/admin cca19df

admin: fix user service listing

---

utils/notifications_utils/recipients.py
utils/notifications_utils/timezones.py
utils/tests/test_letter_timings.py
utils/tests/test_logging.py
utils/tests/test_recipient_csv.py
utils/tests/test_recipient_validation.py
utils/tests/test_timezones.py

Fixed broken unit tests in files
- test_recipient_csv
- test_recipient_validation
- test_timezone

fix broken utils testcases

---

api/README.md
api/app/dao/notifications_dao.py
api/app/v2/notifications/get_notifications.py
api/app/v2/notifications/notification_schemas.py
api/tests/app/v2/notifications/test_get_notifications.py

**Ticket**
https://govausites.atlassian.net/browse/NOT-223
**Example usage**
`GET /v2/notifications?template_id=c671b98c-c1ab-4725-821b-d5278d70b898`
**Example response**
```
{
"links": {
"current": "http://127.0.0.1:6011/v2/notifications?template_id=c671b98c-c1ab-4725-821b-d5278d70b898&template_type=sms&status=delivered&reference=strawberry",
"next": "http://127.0.0.1:6011/v2/notifications?template_id=c671b98c-c1ab-4725-821b-d5278d70b898&template_type=sms&status=delivered&reference=strawberry&older_than=e21cac5d-3590-4333-900b-cb6eea53f72f"
},
"notifications": [
{
"body": "Hello!! Peeps!!!",
"completed_at": "2020-05-14T01:04:58.882353Z",
"created_at": "2020-05-14T01:04:58.774340Z",
"email_address": null,
"id": "5b908c3d-d6cc-408b-9cc0-9c807883b4ee",
"line_1": null,
"line_2": null, …
```

Allow filtering of notifications by template

---

docs/src/code-examples/get-all-messages/dotnet.mdx
docs/src/code-examples/get-all-messages/java.mdx
docs/src/code-examples/get-all-messages/node.mdx
docs/src/code-examples/get-all-messages/python.mdx
docs/src/code-examples/get-message-by-id/dotnet.mdx
docs/src/code-examples/get-message-by-id/go.mdx
docs/src/code-examples/get-message-by-id/node.mdx
docs/src/code-examples/get-message-by-id/python.mdx
docs/src/content/getting-messages.mdx

https://govausites.atlassian.net/browse/NOT-222

Update 'Get message status' documentation (#NOT-222)

---

admin/app/main/views/platform_admin.py
api/app/clients/sms/sap.py
api/app/dao/fact_billing_dao.py
api/app/platform_stats/rest.py

in SMS billing reports, to match our pricing policy

billing: use new international rate calculation

---

api/app/__init__.py
api/app/dao/provider_details_dao.py
api/manifest.yml
api/migrations/versions/0243_disable_twilio.py
api/tests/app/dao/test_provider_details_dao.py
api/tests/app/delivery/test_send_to_providers.py
api/tests/app/provider_details/test_rest.py

Deactivated Twilio from providers list.

Twilio decommission

---

admin/app/__init__.py

looks like this logic was changed here.
https://github.com/govau/notify/commit/8d0635e321432581d3#diff-9c45aa7bd043990584f8fb1966bed486R270

dates: parse dates before assuming they are dt

---

admin/app/templates/views/cookies.html

https://govausites.atlassian.net/browse/NOT-332

Admin: Update cookies page

---

admin/app/main/views/service_settings.py
admin/app/templates/views/service-settings/sms-sender/edit.html

https://govausites.atlassian.net/browse/NOT-341

Improve sender deletion workflow

---

admin/app/main/views/index.py
admin/app/templates/views/security.html

https://govausites.atlassian.net/browse/NOT-342

Update security page

---

admin/app/main/views/manage_users.py
admin/app/notify_client/models.py

this largely exposes the same data as the users page but in an exportable way.
see `manage_users` for source implementation

users: add csv user report for service managers

---

api/app/celery/research_mode_tasks.py
api/app/clients/sms/telstra.py
api/tests/app/celery/test_research_mode_tasks.py

https://github.com/telstra/MessagingAPI-SDK-python/blob/master/Telstra_Messaging/models/status.py

Update Telstra status code (#NOT-399)

---

api/app/celery/service_callback_tasks.py
api/app/dao/callback_failures_dao.py
api/app/notifications/callbacks.py
api/migrations/versions/0249_add_status_callback_index.py

throttle service callbacks if they are failing consistently until conditions improve

status-callbacks: pause when failing

---

admin/app/main/views/platform_admin.py
admin/app/notify_client/platform_stats_api_client.py
admin/app/templates/views/platform-admin/reports.html
api/app/dao/fact_billing_dao.py
api/app/platform_stats/rest.py

corrects the admin billing report to use the same logic as our service
dashboard reports
- collapse billing and usage report into one comprehensive report
- expose entire billing history in one report rather than breaking down
by FY/Quarter
- ignore database rates and use hardcoded domestic/international rates

billing: admin reports reflect service dash
