govau/notify

- admin/app/assets/stylesheets/app.scss
> fix: spreadsheet css had margin causing overflow

- admin/app/main/forms.py
ISM two factor requires a minimum of 6 characters. this just reverts us
back to what UK had which exceeds ISM requirement.
https://acsc.gov.au/publications/Information_Security_Manual_2017_Controls.pdf
page 194, 195
> feat(password-req): set min password length to 8

- admin/manifest-dev.yml
- admin/manifest.yml
- api/manifest-dev.yml
- api/manifest.yml
- status/manifest.yml
CF now prefers using buildpacks instead of buildpack in the manifest
file.
Also formatted the YAML file using prettier.
The error when pushing was:
Deprecation warning: Use of 'buildpack' attribute in manifest is
deprecated in favor of 'buildpacks'. Please see
http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated
for alternatives and other app manifest deprecations. This feature
will be removed in the future.
> fix(manifest): buildpack->buildpacks

- api/app/clients/sms/twilio.py
In development, the Twilio callback URL can end up with an empty host,
so this commit ensures that it's not passed to Twilio of the host is
empty.
> feat(twilio): don't set cb URL if host is empty

- api/migrations/versions/0190_change_templates_to_dta_.py
- api/migrations/versions/0205_fix_email_formatting.py
- utils/.flake8
- utils/notifications_utils/gsm.py
- utils/notifications_utils/template.py
The leading white space causes the paragraph to be formatted as
preformatted text when converted from Markdown to HTML.
> fix(invite): remove leading white space in tmpl

- admin/app/assets/stylesheets/govuk-template.scss
- admin/app/email_domains.yml
Sanity tested the following:
- login with an existing .gov.au login
- send an invite to a .gov.au email address
- send an SMS 
- send an email
- create a new user with .gov.au email address
> Remove gov.uk from list of government email domains + fix css

- admin/Pipfile
- admin/Pipfile.lock
- api/Pipfile
- api/Pipfile.lock
- utils/Pipfile
- utils/Pipfile.lock
Had to add the `pyyaml` transitive-dependency as a direct dependency as `pipenv update` did not update it.
> Fix pyyaml vulnerability

- api/app/dao/services_dao.py
- api/tests/app/dao/test_services_dao.py
When a platform admin creates a service, we usually want to exclude it
from reports because it is often a test or dummy service. We can exclude
it from reports using the count_as_live field. This is set to false for
new services that are created by platform admins. Services of this
nature were already being excluded in the live services report. They are
now excluded from the trial services report too.
It's worth mentioning that count_as_live doesn't make that much sense in
the context of a trial service (since it's not live). We leave the field
named as such for now to keep it aligned with the original GDS codebase.
At the time of writing it appears that a better name is possibly
something like 'include in reports'.
> report: exclude services created by platform admin

- api/Pipfile
- api/Pipfile.lock
- api/app/__init__.py
- api/app/notifications/notifications_ses_callback.py
- utils/.flake8
Adding this piece allows for us to get Notify.gov.au to subscribe to the
SES SNS topic. This endpoint will autoconfirm the subscription when it
is created offline using the AWS CLI.
These changes were extracted out of the greater SES changes due to land
shortly.
> api: add /notifications/email/ses for topic sub

- api/app/celery/research_mode_tasks.py
- api/tests/app/celery/test_research_mode_tasks.py
In a rename the call should have been renamed to
process_ses_results_task.
> api: fix bad task name from refactor

- utils/notifications_utils/template.py
Prior to this change, a smart quote inside an email address would cause
the HTML email link formatting to break.
With this change, smart quotes are now converted to plain quotes inside
an email address.
> email: fix smart quotes formatting

- admin/app/assets/stylesheets/components/email-message.scss
- admin/gulpfile.babel.js
- admin/package.json
- admin/yarn.lock
The lint:sass task was already disabled in our workflow so this does not
really remove anything. It doesn't look like these deps have a fix for
the vulnerability so we're simply removing them for now.
> admin: remove gulp-sass-lint to fix eslint vuln

- admin/app/templates/views/service-settings/email_reply_to.html
This was a missed change from the move to SES and the change to send
from @notify.gov.au.
> admin: fix wrong @digital.gov.au from address

- admin/app/templates/views/templates/choose_history.html
- admin/app/templates/views/templates/template.html
When viewing a templates versions, the heading copy implied that you
were only looking at previous versions of the template when in fact the
topmost version was also the latest.
By using "history of changes" instead, it should be clearer that you're
looking at the full history of changes to the template.
> template: prefer "history" to "versions"

- admin/app/notify_client/service_api_client.py
- admin/tests/app/main/views/test_service_settings.py
- api/migrations/versions/0225_fix_service_message_limit.py
The limit was incorrectly set to 25,000 during the change that set the
SMS message fragment limit to 25,000.
See https://github.com/govau/notify/commit/b29f135dca87aec32daed0a2b41243b6d0bd89be#diff-9ea0fa34caf8fb2b9fbb389ea322bee4L231
> Fix message limit on services (25,000->250,000)

- admin/app/__init__.py
- admin/app/asset_fingerprinter.py
- admin/app/notify_client/api_key_api_client.py
- admin/app/notify_client/billing_api_client.py
- admin/app/notify_client/email_branding_client.py
- admin/app/notify_client/events_api_client.py
- admin/app/notify_client/inbound_number_client.py
- admin/app/notify_client/invite_api_client.py
- admin/app/notify_client/job_api_client.py
- admin/app/notify_client/letter_jobs_client.py
- admin/app/notify_client/notification_api_client.py
- admin/app/notify_client/org_invite_api_client.py
- admin/app/notify_client/organisations_api_client.py
- admin/app/notify_client/provider_client.py
- admin/app/notify_client/service_api_client.py
- admin/app/notify_client/status_api_client.py
- admin/app/notify_client/support_api_client.py
- admin/app/notify_client/template_statistics_api_client.py
- admin/app/notify_client/user_api_client.py
This avoids the annoying problem where you can't import a client unless
the app has already been initialised.
See https://github.com/alphagov/notifications-admin/commit/9e798506c5aeb2749b8f766bdba168a48e661892
> admin: initialise clients outside the app

- admin/app/assets/javascripts/fullscreenTable.js
- admin/app/assets/javascripts/main.js
- admin/app/assets/javascripts/stick-to-window-when-scrolling.js
- admin/app/assets/stylesheets/components/fullscreen-table.scss
- admin/app/assets/stylesheets/components/stick-at-top-when-scrolling.scss
- admin/app/notify_client/job_api_client.py
- admin/app/templates/components/page-footer.html
- admin/app/templates/components/page-header.html
- admin/app/templates/components/table.html
- admin/app/templates/views/edit-email-template.html
- admin/app/templates/views/edit-letter-template.html
- admin/app/templates/views/edit-sms-template.html
- admin/app/templates/views/notifications/check.html
- admin/app/templates/views/service-settings/set-email-branding.html
- admin/gulpfile.babel.js
- admin/tests/app/main/views/test_dashboard.py
- admin/tests/app/main/views/test_send.py
- admin/tests/conftest.py
Applied to:
- email and SMS template pages
- send one-off email/SMS page
- set service email branding page
There are many other pages we can introduce sticky footers/buttons such
as API keys and email reply addresses.
> admin: add sticky footer

- api/migrations/versions/0227_invited_users_folder_permissions.py
- api/migrations/versions/0228_add_letter_branding_table.py
- api/migrations/versions/0229_organisation_fields_and_domain.py
- api/migrations/versions/0230_service_data_retention.py
In preparation for large update. All DB changes can be made without
affecting existing data.
> api: add DB migrations

- api/app/dao/services_dao.py
- api/tests/app/dao/test_services_dao.py
across type, status, for the current day.
Results could be inconsistent depending on whether there were multiple
notification statuses out at the time of check, or even if there are
multiple templates per service.
This is a bug that is especially prominent when redis is disabled.
originally surfaced here:
alphagov/notifications-api@e3d4185
This was introduced through a refactor to make this check more efficient --
Originally there was a helper function that collected some stats to be
displayed somewhere. This helper was also being used here to seed message
limit counts by totalling all the stats. When this was refactored it was
mistakenly decided to keep the "group by" clause BUT also to stop adding up
all the groups of stats.
We could have reverted to the old behaviour and added stats …
> api/rate-limits: aggregate notification count

- admin/app/__init__.py
- admin/app/main/views/sign_in.py
- admin/tests/app/main/views/test_dashboard.py
We came across an issue with one session that was possibly corrupted. It
resulted in infinite redirects to the /sign-in page. This seems to have
been caused by the sign in route thinking that there is a current_user
and that the current_user.is_authenticated, however the Flask
login_required decorator disagreed with this state. This caused the
Flask decorator to redirect to the login_manager.unauthorized_handler
handler, which in turn would redirect back to /sign-in. This caused the
infinite redirect.
To fix this, we ensure that logout_user is called in the
unauthorized_handler. This should be OK since the user should already be
logged out if we enter this handler.
> admin: force user log out when signing in again

- admin/app/main/__init__.py
- admin/app/main/forms.py
- admin/app/main/views/find_users.py
- admin/app/models/__init__.py
- admin/app/models/organisation.py
- admin/app/models/roles_and_permissions.py
- admin/app/models/service.py
- admin/app/models/template_list.py
- admin/app/models/user.py
- admin/app/notify_client/__init__.py
- admin/app/notify_client/user_api_client.py
- admin/app/templates/views/find-users/find-users-by-email.html
- admin/app/templates/views/find-users/user-information.html
- admin/app/templates/views/platform-admin/_base_template.html
- admin/tests/app/main/views/test_find_users.py
This brings in the bare minimum needed to wire up these pages. The
admin/app/models/*.py files are not all required, but it was easier to
just bring in the entire folder and just disable some parts of it that
imported more things (that would have caused cascading imports).
> admin: add pages to find and archive users

- api/app/clients/sms/telstra.py
- api/app/commands.py
Invoke as:
pipenv run flask command get-telstra-message-status -m <message_id>
If successful, output looks like:
Sent to: +61412345678
Sent at: 2019-09-03T11:09:03+10:00
Received at: 2019-09-03T11:09:21+10:00
Telstra status: DELIVRD
Notify status: delivered
The `Notify status` line is helpful in order to see how Notify has
mapped the Telstra status to our internal status.
> script: add command to get Telstra message status

- admin/app/assets/stylesheets/components/overrides.scss
- admin/app/assets/stylesheets/components/table.scss
Also remove negative margin on table show more link. With the removal of
the override above the show more link ends up squashing up into the last
row of the table.
> admin: remove overrides for filenames in table

- .circleci/config.yml
- admin/README.md
- admin/package.json
- admin/yarn.lock
gulp-base64 was tagged a while back, but we didn't update package.json
to pull in that change.
It was discovered that the Node frontend will not work on 13.x so this
commit also pins it to 10.x. In order for a 10.x to be pulled in by
CircleCI, the circleci/python image needed to be updated to 3.6.8-node.
Also tidy up some fields in package.json.
> admin: update gulp-base64, pin Node version

- api/manifest-dev.yml
Reaching CF org memory limit. Need to move on so reducing instances to 1. 4 would be better because it means that feature environments are more
like prod, but oh well.
> api: move back to 1 instance for dev due to limits

- api/app/celery/reporting_tasks.py
- api/app/celery/scheduled_tasks.py
- api/app/dao/dao_utils.py
SQS is at-least-once message delivery which means these celery
task handlers may fire more than once. If there is a duplicate
key IntegrityError it means that the task message was
delivered more than once.
> api: ignore IntegrityError in celery task handler

- api/app/commands.py
- api/app/dao/jobs_dao.py
- api/tests/app/dao/test_jobs_dao.py
This allows us to quickly debug the state of jobs and is a faster
solution than writing an integration between the platform admin
frontend and the API.
> api: add commands to print jobs to CSV

- .circleci/config.yml
- Makefile
- README.md
- api/Makefile
- api/manifest-dev.yml
- api/manifest.yml
- ci/Makefile
- ci/undeploy_closed_branches.py
The aim of this change is to ensure that bad tasks that end up in
certain queues cannot possibly block other important queues that need to
be processed. It was observed that a service callback task appeared to
starve the workers which resulted in other queues not being processed.
This change splits out the service callbacks into its own worker app.
There is still a chance that a bad service callback task can affect
other good service callbacks and a later commit should explore a fix to
that particular issue. However, this change should reduce the surface
area that such a bug can affect.
The 6 groups of workers introduced in this change are:
- sender: processes tasks to send email and send SMS
- priority: processes priority tasks (most importantly any template in
Notify that is given the …
> celery: split out worker app into 6 groups

- api/app/celery/service_callback_tasks.py
The default retry strategy will try 3 times, meaning a request and
worker thread can be blocked for a minimum of 180s. Reducing this to 15s
means that the time is reduced to 45s. This is just an improvement to
the problem, not a final solution.
> service-callbacks: change timeout from 60s to 15s

- docs/src/content/integration-testing.mdx
until we can get some that we're in control of
> docs: undocument use of smoke test ph numbers

- admin/app/main/views/service_settings.py
Upon testing master branch, I was seeing the `403` response upon delete. Made some tweaks to `service_delete_sms_sender`.
> Fix bug whereby sender is not deleted

- api/app/celery/scheduled_tasks.py
- api/app/dao/notifications_dao.py
- api/tests/app/dao/notification_dao/test_notification_dao.py
no longer include notifications that were sent with a test key or
that have no reference to search for
> status: restrict which notifications we check on

- api/app/celery/service_callback_tasks.py
we were attempting to store "None" when we should have stored null.
> cb-failures: record null service,apikey correctly

- api/app/dao/notifications_dao.py
we're not able to go out and check these statuses, so don't bother
pulling them from the database yet.
> status-checks: only check sms status in query

- api/app/celery/research_mode_tasks.py
- api/tests/app/celery/test_research_mode_tasks.py
and now properly imitate sap oauth2 callbacks
> callbacks: re-support for test-key status updates

- api/app/models.py
- api/tests/app/db.py
- api/tests/app/test_model.py
- api/tests/app/v2/notifications/test_get_notifications.py
- docs/src/code-examples/get-message-by-id/dotnet.mdx
expose created_by_email_address and created_by_name fields on our
notification endpoints for notificications that have been sent as a
one-off through the Notify admin interface
> api: expose user creation fields on notifications

- admin/Pipfile
- admin/Pipfile.lock
transitive dependencies were being upgraded out from underneath us.
this change brings them back down to major versions that notify supports.
> deps: major version selector on  wtforms, PyJWT
